"""followers

Revision ID: 96da3eb9ca06
Revises: bafdcc4f066e
Create Date: 2019-07-27 23:41:15.197395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96da3eb9ca06'
down_revision = 'bafdcc4f066e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
